export const SLASHING_PERIOD = 10000
export const POST_TX_CHECK_LIMIT = 30
export const UTC_OFFSET_OF_SEOUL_IN_MIN = 540
export const TERRA_ACCOUNT_REGEX = /^terra1(?:[a-z0-9]{38}|[a-z0-9]{58})$/
export const TERRA_OPERATOR_ADD_REGEX = /^terravaloper1[a-z0-9]{38}$/
export const CHAIN_ID_REGEX = /^[a-zA-Z0-9-]{1,32}$/
export const MOVING_AVG_WINDOW_IN_DAYS = 10
export const DAYS_IN_YEAR = 365
export const ONE_DAY_IN_MS = 60000 * 60 * 24
export const LOCAL_TERRA_CHAIN_ID = 'localterra'
export const BOND_DENOM = 'uluna'
