export const SLASHING_PERIOD = 10000
export const POST_TX_CHECK_LIMIT = 30
export const UTC_OFFSET_OF_SEOUL_IN_MIN = 540
export const TERRA_ACCOUNT_REGEX = /^terra1[a-z0-9]{38}$/
export const TERRA_OPERATOR_ADD_REGEX = /^terravaloper1[a-z0-9]{38}$/
export const MOVING_AVG_WINDOW_IN_DAYS = 7
export const DAYS_IN_YEAR = 365
export const CORS_REGEXP = /^https:\/\/(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.){0,3}(terra\.money|terra\.dev|station\.terra-project\.now\.sh)(?::\d{4,5})?(?:\/|$)/
export const ONE_DAY_IN_MS = 60000 * 60 * 24
export const LOCAL_TERRA_CHAIN_ID = 'localterra'
export const PROMISE_MAX_TIMEOUT_MS = 60 * 1000 // in ms
export const PROMISE_TIMEOUT_TEN_MIN_IN_MS = 10 * PROMISE_MAX_TIMEOUT_MS // 10 min in milliseconds
export const PROMISE_TIMEOUT_TWENTY_MIN_IN_MS = 2 * PROMISE_TIMEOUT_TEN_MIN_IN_MS // 10 min in milliseconds
